name = "nextjs-cloudflare-shop"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "shop-database"
# database_id = "280abe63-fcc3-431f-9662-7410cadd285d"  # 在创建数据库后替换为实际的ID

[vars]
ENVIRONMENT = "production"